/*
Copyright 2019 Esri
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.​
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Issues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Issues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$safeprojectname$.Properties.Issues", typeof(Issues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address type is required.
        /// </summary>
        public static string addressType_REQ {
            get {
                return ResourceManager.GetString("addressType_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state is required.
        /// </summary>
        public static string adminArea_FGDC_REQ {
            get {
                return ResourceManager.GetString("adminArea_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin area is required.
        /// </summary>
        public static string adminArea_REQ {
            get {
                return ResourceManager.GetString("adminArea_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a citation or an identifier must be provided.
        /// </summary>
        public static string aggrInfo_REQ {
            get {
                return ResourceManager.GetString("aggrInfo_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to association type is required.
        /// </summary>
        public static string AscTypeCd_REQ {
            get {
                return ResourceManager.GetString("AscTypeCd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute precision must be an integer.
        /// </summary>
        public static string atprecis_INTEGER {
            get {
                return ResourceManager.GetString("atprecis_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute description is required.
        /// </summary>
        public static string attDesc_REQ {
            get {
                return ResourceManager.GetString("attDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an attribute definition is required.
        /// </summary>
        public static string attrdef_REQ {
            get {
                return ResourceManager.GetString("attrdef_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute definition source is required.
        /// </summary>
        public static string attrdefs_REQ {
            get {
                return ResourceManager.GetString("attrdefs_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one type of attribute domain is required.
        /// </summary>
        public static string attrdomv_REQ {
            get {
                return ResourceManager.GetString("attrdomv_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute label is required.
        /// </summary>
        public static string attrlabl_REQ {
            get {
                return ResourceManager.GetString("attrlabl_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measurement resolution must be a real value.
        /// </summary>
        public static string attrmres_REAL {
            get {
                return ResourceManager.GetString("attrmres_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute type is required.
        /// </summary>
        public static string attrtype_REQ {
            get {
                return ResourceManager.GetString("attrtype_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value accuracy must be a real value.
        /// </summary>
        public static string attrva_REAL {
            get {
                return ResourceManager.GetString("attrva_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute scale must be an integer.
        /// </summary>
        public static string attscale_INTEGER {
            get {
                return ResourceManager.GetString("attscale_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute width must be an integer.
        /// </summary>
        public static string attwidth_INTEGER {
            get {
                return ResourceManager.GetString("attwidth_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute width is required.
        /// </summary>
        public static string attwidth_REQ {
            get {
                return ResourceManager.GetString("attwidth_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to azimuth angle must be in the range of 0...360.
        /// </summary>
        public static string AZIM_ANGLE_BND {
            get {
                return ResourceManager.GetString("AZIM_ANGLE_BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to band minimum value must be less than the maximum value.
        /// </summary>
        public static string band_minMaxBoundsError {
            get {
                return ResourceManager.GetString("band_minMaxBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse graphic description is required.
        /// </summary>
        public static string bgFileDesc_REQ {
            get {
                return ResourceManager.GetString("bgFileDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse graphic filename is required.
        /// </summary>
        public static string bgFileName_REQ {
            get {
                return ResourceManager.GetString("bgFileName_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse graphic file type is required.
        /// </summary>
        public static string bgFileType_REQ {
            get {
                return ResourceManager.GetString("bgFileType_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits per value must be an integer.
        /// </summary>
        public static string bitsPerVal_INTEGER {
            get {
                return ResourceManager.GetString("bitsPerVal_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cell geometry code is required.
        /// </summary>
        public static string cellGeo_REQ {
            get {
                return ResourceManager.GetString("cellGeo_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a check point description is required.
        /// </summary>
        public static string chkPtDesc_REQ {
            get {
                return ResourceManager.GetString("chkPtDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city is required.
        /// </summary>
        public static string city_REQ {
            get {
                return ResourceManager.GetString("city_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classification code is required.
        /// </summary>
        public static string ClasscationCd_REQ {
            get {
                return ResourceManager.GetString("ClasscationCd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to classification system is required.
        /// </summary>
        public static string classSys_REQ {
            get {
                return ResourceManager.GetString("classSys_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloud cover percentage must be in the range of 0...100.
        /// </summary>
        public static string CLOUDCOVER_PER {
            get {
                return ResourceManager.GetString("CLOUDCOVER_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address information is required.
        /// </summary>
        public static string cntAddress_FGDC_REQ {
            get {
                return ResourceManager.GetString("cntAddress_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codelist name is required.
        /// </summary>
        public static string codesetn_REQ {
            get {
                return ResourceManager.GetString("codesetn_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codelist source is required.
        /// </summary>
        public static string codesets_REQ {
            get {
                return ResourceManager.GetString("codesets_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conformance result explanation is required.
        /// </summary>
        public static string conExpl_REQ {
            get {
                return ResourceManager.GetString("conExpl_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conformance pass value is required.
        /// </summary>
        public static string conPass_REQ {
            get {
                return ResourceManager.GetString("conPass_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conformance specification is required.
        /// </summary>
        public static string conSpec_REQ {
            get {
                return ResourceManager.GetString("conSpec_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content type code is required.
        /// </summary>
        public static string ContentTypCd_REQ {
            get {
                return ResourceManager.GetString("ContentTypCd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country code is required.
        /// </summary>
        public static string countryCode_REQ {
            get {
                return ResourceManager.GetString("countryCode_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupling code is required.
        /// </summary>
        public static string CouplTypCd_REQ {
            get {
                return ResourceManager.GetString("CouplTypCd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bounding coordinates are required.
        /// </summary>
        public static string dataExtBBoxReq_FGDC {
            get {
                return ResourceManager.GetString("dataExtBBoxReq_FGDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if data quality reports are provided, a process step is required.
        /// </summary>
        public static string dataLineage_FGDC_REQ {
            get {
                return ResourceManager.GetString("dataLineage_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if scope is &quot;dataset&quot; or &quot;series&quot;, one of process step, data source, or lineage statement is required.
        /// </summary>
        public static string dataLineage_REQ {
            get {
                return ResourceManager.GetString("dataLineage_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series name and issue id are required.
        /// </summary>
        public static string datasetSeries_FGDC_REQ {
            get {
                return ResourceManager.GetString("datasetSeries_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to within a data source, an extent or a citation is required.
        /// </summary>
        public static string dataSource_NAP_REQ {
            get {
                return ResourceManager.GetString("dataSource_NAP_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to within data source, either an extent or a description must be provided..
        /// </summary>
        public static string dataSource_REQ {
            get {
                return ResourceManager.GetString("dataSource_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one date is required.
        /// </summary>
        public static string dates_REQ {
            get {
                return ResourceManager.GetString("dates_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimension size must be an integer.
        /// </summary>
        public static string dimSize_INTEGER {
            get {
                return ResourceManager.GetString("dimSize_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimension size is required.
        /// </summary>
        public static string dimSize_REQ {
            get {
                return ResourceManager.GetString("dimSize_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to axis dimension is required.
        /// </summary>
        public static string DimType_REQ {
            get {
                return ResourceManager.GetString("DimType_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discipline keywords are required.
        /// </summary>
        public static string disciplineKeywords_REQ {
            get {
                return ResourceManager.GetString("disciplineKeywords_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a list of double values is required.
        /// </summary>
        public static string doubleList_REQ {
            get {
                return ResourceManager.GetString("doubleList_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lineage or data quality report is required for datasets.
        /// </summary>
        public static string dq_dataset_REQ {
            get {
                return ResourceManager.GetString("dq_dataset_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to either a conformance result or a quantitative result is required.
        /// </summary>
        public static string dq_report_REQ {
            get {
                return ResourceManager.GetString("dq_report_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completeness omission report is required.
        /// </summary>
        public static string DQCompOm_REQ {
            get {
                return ResourceManager.GetString("DQCompOm_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conceptual consistency report is required.
        /// </summary>
        public static string DQConcConsis_REQ {
            get {
                return ResourceManager.GetString("DQConcConsis_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conformance result required for domain consistency report.
        /// </summary>
        public static string DQDomConsis_Report_REQ {
            get {
                return ResourceManager.GetString("DQDomConsis_Report_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one domain consistency report is required.
        /// </summary>
        public static string DQDomConsis_REQ {
            get {
                return ResourceManager.GetString("DQDomConsis_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if scope is &quot;dataset&quot; or &quot;series&quot;, a data quality section is required.
        /// </summary>
        public static string dqInfo_REQ {
            get {
                return ResourceManager.GetString("dqInfo_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there must be exactly one data quality section &quot;scoped to the full resource&quot;, i.e. scoped either &quot;dataset&quot; or &quot;series&quot;.
        /// </summary>
        public static string dqScope_INSPIRE_REQ {
            get {
                return ResourceManager.GetString("dqScope_INSPIRE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a lineage statement is mandatory in the data quality section that addresses the full resource for datasets and series.
        /// </summary>
        public static string dqStatement_INSPIRE_REQ {
            get {
                return ResourceManager.GetString("dqStatement_INSPIRE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domain value is required.
        /// </summary>
        public static string edomv_REQ {
            get {
                return ResourceManager.GetString("edomv_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domain value description is required.
        /// </summary>
        public static string edomvd_REQ {
            get {
                return ResourceManager.GetString("edomvd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domain value definition source is required.
        /// </summary>
        public static string edomvds_REQ {
            get {
                return ResourceManager.GetString("edomvds_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elevation angle must be in the range of -90...90.
        /// </summary>
        public static string ELEV_ANGLE_BND {
            get {
                return ResourceManager.GetString("ELEV_ANGLE_BND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address is required.
        /// </summary>
        public static string eMailAdd_REQ {
            get {
                return ResourceManager.GetString("eMailAdd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity type definition is required.
        /// </summary>
        public static string enttypd_REQ {
            get {
                return ResourceManager.GetString("enttypd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity type definition source is required.
        /// </summary>
        public static string enttypds_REQ {
            get {
                return ResourceManager.GetString("enttypds_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity type label is required.
        /// </summary>
        public static string enttypl_REQ {
            get {
                return ResourceManager.GetString("enttypl_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluation method description is required.
        /// </summary>
        public static string evalMethDesc_REQ {
            get {
                return ResourceManager.GetString("evalMethDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coordinate is required.
        /// </summary>
        public static string extent_coord_REQ {
            get {
                return ResourceManager.GetString("extent_coord_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time instants are not allowed.
        /// </summary>
        public static string extent_dataExt_NAP_REQ {
            get {
                return ResourceManager.GetString("extent_dataExt_NAP_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to either a bounding box or a geographic description (identifier) must be provided if the item&apos;s hierarchy level is &quot;dataset&quot;.
        /// </summary>
        public static string extent_dataExt_REQ {
            get {
                return ResourceManager.GetString("extent_dataExt_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bounding box must be provided if the item&apos;s hierarchy level is &quot;dataset&quot;.
        /// </summary>
        public static string extent_dataExtBBox_REQ {
            get {
                return ResourceManager.GetString("extent_dataExtBBox_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description is required if a temporal extent is provided.
        /// </summary>
        public static string extent_dataExtDesc_REQ {
            get {
                return ResourceManager.GetString("extent_dataExtDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one geographic bounding box must be provided.
        /// </summary>
        public static string extent_dataExtGeoBndBoxReq {
            get {
                return ResourceManager.GetString("extent_dataExtGeoBndBoxReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a bounding box or a geographic description is required if the hierarchy level is &quot;service&quot; or service information is present.
        /// </summary>
        public static string extent_dataExtService_REQ {
            get {
                return ResourceManager.GetString("extent_dataExtService_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temporal extent is required.
        /// </summary>
        public static string extent_dataExtTemp_REQ {
            get {
                return ResourceManager.GetString("extent_dataExtTemp_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south latitude must be less than north latitude.
        /// </summary>
        public static string extent_latBoundsError {
            get {
                return ResourceManager.GetString("extent_latBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west longitude must be less than east longitude.
        /// </summary>
        public static string extent_lonBoundsError {
            get {
                return ResourceManager.GetString("extent_lonBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format name is required.
        /// </summary>
        public static string formatName_REQ {
            get {
                return ResourceManager.GetString("formatName_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format version is required.
        /// </summary>
        public static string formatVer_REQ {
            get {
                return ResourceManager.GetString("formatVer_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object count must be an integer.
        /// </summary>
        public static string geoObjCnt_INTEGER {
            get {
                return ResourceManager.GetString("geoObjCnt_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometric object count is required.
        /// </summary>
        public static string geoObjCnt_REQ {
            get {
                return ResourceManager.GetString("geoObjCnt_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geometric object type is required.
        /// </summary>
        public static string GeoObjTypCd_REQ {
            get {
                return ResourceManager.GetString("GeoObjTypCd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to georeferenced parameters are required.
        /// </summary>
        public static string georefPars_REQ {
            get {
                return ResourceManager.GetString("georefPars_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to handling description is required.
        /// </summary>
        public static string handDesc_REQ {
            get {
                return ResourceManager.GetString("handDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abstract is required.
        /// </summary>
        public static string idAbs_REQ {
            get {
                return ResourceManager.GetString("idAbs_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identifier code is required.
        /// </summary>
        public static string identCode_REQ {
            get {
                return ResourceManager.GetString("identCode_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purpose is required.
        /// </summary>
        public static string idPurp_REQ {
            get {
                return ResourceManager.GetString("idPurp_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status code is required.
        /// </summary>
        public static string idStatus_REQ {
            get {
                return ResourceManager.GetString("idStatus_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to integer value is required.
        /// </summary>
        public static string INTEGER_REQ {
            get {
                return ResourceManager.GetString("INTEGER_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language is required.
        /// </summary>
        public static string language_REQ {
            get {
                return ResourceManager.GetString("language_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language must be one of the 23 EU official languages.
        /// </summary>
        public static string languageCode_EU_REQ {
            get {
                return ResourceManager.GetString("languageCode_EU_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language is required.
        /// </summary>
        public static string languageCode_REQ {
            get {
                return ResourceManager.GetString("languageCode_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude coordinate must be a real value.
        /// </summary>
        public static string LAT_COORD_REAL_REQ {
            get {
                return ResourceManager.GetString("LAT_COORD_REAL_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude coordinates must be real values in the range of -90.0...90.0.
        /// </summary>
        public static string LAT_COORD_REQ {
            get {
                return ResourceManager.GetString("LAT_COORD_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkage URL is required.
        /// </summary>
        public static string linkage_REQ {
            get {
                return ResourceManager.GetString("linkage_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitude coordinate must be a real value.
        /// </summary>
        public static string LON_COORD_REAL_REQ {
            get {
                return ResourceManager.GetString("LON_COORD_REAL_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitude coordinates must be real values in the range of -180.0...180.0.
        /// </summary>
        public static string LON_COORD_REQ {
            get {
                return ResourceManager.GetString("LON_COORD_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenance frequency code is required.
        /// </summary>
        public static string maintFreq_REQ {
            get {
                return ResourceManager.GetString("maintFreq_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maintenance scope code is required.
        /// </summary>
        public static string maintScp_REQ {
            get {
                return ResourceManager.GetString("maintScp_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum value must be a real value.
        /// </summary>
        public static string maxVal_REAL {
            get {
                return ResourceManager.GetString("maxVal_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character set of &apos;utf8&apos; is required.
        /// </summary>
        public static string mdChar_REQ {
            get {
                return ResourceManager.GetString("mdChar_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata datestamp is required.
        /// </summary>
        public static string mdDateSt_REQ {
            get {
                return ResourceManager.GetString("mdDateSt_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file identifier is required.
        /// </summary>
        public static string mdFileID_REQ {
            get {
                return ResourceManager.GetString("mdFileID_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hierarchy level is required.
        /// </summary>
        public static string mdHrLv_REQ {
            get {
                return ResourceManager.GetString("mdHrLv_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hierarchy level name is required.
        /// </summary>
        public static string mdHrLvName_REQ {
            get {
                return ResourceManager.GetString("mdHrLvName_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measure description is required.
        /// </summary>
        public static string measDesc_REQ {
            get {
                return ResourceManager.GetString("measDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium density must be a real value greater than zero.
        /// </summary>
        public static string medDensity_REAL {
            get {
                return ResourceManager.GetString("medDensity_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if a density value is provided, the density units is required.
        /// </summary>
        public static string medDenUnits_REQ {
            get {
                return ResourceManager.GetString("medDenUnits_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of volumes must be an integer greater than zero.
        /// </summary>
        public static string medVol_INTEGER {
            get {
                return ResourceManager.GetString("medVol_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one metadata contact is required.
        /// </summary>
        public static string metadataContact_REQ {
            get {
                return ResourceManager.GetString("metadataContact_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to both minimum and maximum band values are required.
        /// </summary>
        public static string MinMaxVal_REQ {
            get {
                return ResourceManager.GetString("MinMaxVal_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum value must be a real value.
        /// </summary>
        public static string minVal_REAL {
            get {
                return ResourceManager.GetString("minVal_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of dimensions must be an integer.
        /// </summary>
        public static string numDims_INTEGER {
            get {
                return ResourceManager.GetString("numDims_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of dimensions is required.
        /// </summary>
        public static string numDims_REQ {
            get {
                return ResourceManager.GetString("numDims_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset must be a real value.
        /// </summary>
        public static string offset_REAL {
            get {
                return ResourceManager.GetString("offset_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization name is required.
        /// </summary>
        public static string OrgName_REQ {
            get {
                return ResourceManager.GetString("OrgName_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an originator is required.
        /// </summary>
        public static string originator_FGDC_REQ {
            get {
                return ResourceManager.GetString("originator_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;other contraints&quot; is requried.
        /// </summary>
        public static string othConsts_REQ {
            get {
                return ResourceManager.GetString("othConsts_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;other&quot; keywords are required.
        /// </summary>
        public static string otherKeywords_REQ {
            get {
                return ResourceManager.GetString("otherKeywords_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name, organization or position is required for the responsible party..
        /// </summary>
        public static string party_REQ {
            get {
                return ResourceManager.GetString("party_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name or organization is required.
        /// </summary>
        public static string partyFgdc_FGDC_REQ {
            get {
                return ResourceManager.GetString("partyFgdc_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to peak response must be a real value.
        /// </summary>
        public static string pkResp_REAL {
            get {
                return ResourceManager.GetString("pkResp_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place keywords are required.
        /// </summary>
        public static string placeKeywords_REQ {
            get {
                return ResourceManager.GetString("placeKeywords_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post code is required.
        /// </summary>
        public static string postCode_REQ {
            get {
                return ResourceManager.GetString("postCode_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product keywords are requried.
        /// </summary>
        public static string productKeywords_REQ {
            get {
                return ResourceManager.GetString("productKeywords_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protocol is required.
        /// </summary>
        public static string protocol_REQ {
            get {
                return ResourceManager.GetString("protocol_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixel orientation code is required.
        /// </summary>
        public static string ptInPixel_REQ {
            get {
                return ResourceManager.GetString("ptInPixel_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to publication date is required.
        /// </summary>
        public static string pubDate_FGDC_REQ {
            get {
                return ResourceManager.GetString("pubDate_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name or organization for publishers is required.
        /// </summary>
        public static string publisher_FGDC_REQ {
            get {
                return ResourceManager.GetString("publisher_FGDC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantitative value is required.
        /// </summary>
        public static string quanVal_REQ {
            get {
                return ResourceManager.GetString("quanVal_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attribute range domain minimum value must be less than the maximum value.
        /// </summary>
        public static string rdomain_minMaxError {
            get {
                return ResourceManager.GetString("rdomain_minMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum for range domain must be real vaue.
        /// </summary>
        public static string rdommax_REAL {
            get {
                return ResourceManager.GetString("rdommax_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum range value is required.
        /// </summary>
        public static string rdommax_REQ {
            get {
                return ResourceManager.GetString("rdommax_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mean for range domain must be a real value.
        /// </summary>
        public static string rdommean_REAL {
            get {
                return ResourceManager.GetString("rdommean_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum for range domain must be a real value.
        /// </summary>
        public static string rdommin_REAL {
            get {
                return ResourceManager.GetString("rdommin_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum range value is required.
        /// </summary>
        public static string rdommin_REQ {
            get {
                return ResourceManager.GetString("rdommin_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard deviation for range domain must be a real value.
        /// </summary>
        public static string rdomstdv_REAL {
            get {
                return ResourceManager.GetString("rdomstdv_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference system identifier is required.
        /// </summary>
        public static string refSysID_REQ {
            get {
                return ResourceManager.GetString("refSysID_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference system dimension is required.
        /// </summary>
        public static string RefSystem_dimension_REQ {
            get {
                return ResourceManager.GetString("RefSystem_dimension_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference system is required for the spatial reference type.
        /// </summary>
        public static string RefSystem_REQ {
            get {
                return ResourceManager.GetString("RefSystem_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report type is required.
        /// </summary>
        public static string ReportType_REQ {
            get {
                return ResourceManager.GetString("ReportType_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one legal constraint code or security classification code is required.
        /// </summary>
        public static string resConst_REQ {
            get {
                return ResourceManager.GetString("resConst_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title is required.
        /// </summary>
        public static string resTitle_REQ {
            get {
                return ResourceManager.GetString("resTitle_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denominator must be an integer greater than 0.
        /// </summary>
        public static string rfDenom_INTEGER {
            get {
                return ResourceManager.GetString("rfDenom_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role required to be &apos;point of contact&apos;.
        /// </summary>
        public static string role_POC_REQ {
            get {
                return ResourceManager.GetString("role_POC_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to role is required.
        /// </summary>
        public static string role_REQ {
            get {
                return ResourceManager.GetString("role_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to included with dataset is required.
        /// </summary>
        public static string rpCntInfo_incWithDS {
            get {
                return ResourceManager.GetString("rpCntInfo_incWithDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number, address or link required.
        /// </summary>
        public static string rpCntInfo_NAP_REQ {
            get {
                return ResourceManager.GetString("rpCntInfo_NAP_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization name required.
        /// </summary>
        public static string rpOrgName_REQ {
            get {
                return ResourceManager.GetString("rpOrgName_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scale factor must be a real value.
        /// </summary>
        public static string sclFac_REAL {
            get {
                return ResourceManager.GetString("sclFac_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scope level is required.
        /// </summary>
        public static string ScopeCd_REQ {
            get {
                return ResourceManager.GetString("ScopeCd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scope level description is required.
        /// </summary>
        public static string scpLvlDesc_REQ {
            get {
                return ResourceManager.GetString("scpLvlDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to script title is required.
        /// </summary>
        public static string scriptTitle_REQ {
            get {
                return ResourceManager.GetString("scriptTitle_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tags are required.
        /// </summary>
        public static string searchKeys_REQ {
            get {
                return ResourceManager.GetString("searchKeys_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a valid sequence identifier is required.
        /// </summary>
        public static string seqID_REQ {
            get {
                return ResourceManager.GetString("seqID_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spatial representation type code is required.
        /// </summary>
        public static string SpatRepTypCd_REQ {
            get {
                return ResourceManager.GetString("SpatRepTypCd_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to specific usage is required.
        /// </summary>
        public static string specUsage_REQ {
            get {
                return ResourceManager.GetString("specUsage_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to within a data source, a descripion is required.
        /// </summary>
        public static string srcDesc_REQ {
            get {
                return ResourceManager.GetString("srcDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process date is required.
        /// </summary>
        public static string stepDateTm_REQ {
            get {
                return ResourceManager.GetString("stepDateTm_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process step description is required.
        /// </summary>
        public static string stepDesc_REQ {
            get {
                return ResourceManager.GetString("stepDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stratum keywords are required.
        /// </summary>
        public static string stratumKeywords_REQ {
            get {
                return ResourceManager.GetString("stratumKeywords_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coupled resource information is required.
        /// </summary>
        public static string svCouplRes_REQ {
            get {
                return ResourceManager.GetString("svCouplRes_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service type name is required.
        /// </summary>
        public static string svType_REQ {
            get {
                return ResourceManager.GetString("svType_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a tag, topic or theme keyword is required.
        /// </summary>
        public static string tagTopicKeyword_REQ {
            get {
                return ResourceManager.GetString("tagTopicKeyword_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description is required for temporal extents.
        /// </summary>
        public static string tempEle_exDesc_REQ {
            get {
                return ResourceManager.GetString("tempEle_exDesc_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temporal keywords are required.
        /// </summary>
        public static string temporalKeywords_REQ {
            get {
                return ResourceManager.GetString("temporalKeywords_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theme keywords are required.
        /// </summary>
        public static string themeKeywords_REQ {
            get {
                return ResourceManager.GetString("themeKeywords_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tone gradiation must be an integer.
        /// </summary>
        public static string toneGrad_INTEGER {
            get {
                return ResourceManager.GetString("toneGrad_INTEGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool summary is required.
        /// </summary>
        public static string toolSummary_REQ {
            get {
                return ResourceManager.GetString("toolSummary_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to topic category is required.
        /// </summary>
        public static string topics_REQ {
            get {
                return ResourceManager.GetString("topics_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer size must be a real value greater than zero.
        /// </summary>
        public static string transSize_REAL {
            get {
                return ResourceManager.GetString("transSize_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value units is required.
        /// </summary>
        public static string UOM_REQ {
            get {
                return ResourceManager.GetString("UOM_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use limitation is required.
        /// </summary>
        public static string useLimit_REQ {
            get {
                return ResourceManager.GetString("useLimit_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legal constraints use limitation is required when distributor information is provided.
        /// </summary>
        public static string useLimitDist_REQ {
            get {
                return ResourceManager.GetString("useLimitDist_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to values for measures must be integer or real numbers.
        /// </summary>
        public static string ValueUOM_Real {
            get {
                return ResourceManager.GetString("ValueUOM_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to units are requried for measures.
        /// </summary>
        public static string ValueUoMUnits_REQ {
            get {
                return ResourceManager.GetString("ValueUoMUnits_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value units are required.
        /// </summary>
        public static string valUnit_REQ {
            get {
                return ResourceManager.GetString("valUnit_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical maximum extent must be a real value.
        /// </summary>
        public static string vertMaxVal_REAL {
            get {
                return ResourceManager.GetString("vertMaxVal_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical maximum extent is required.
        /// </summary>
        public static string vertMaxVal_REQ {
            get {
                return ResourceManager.GetString("vertMaxVal_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical minimum must be less than vertical maximum.
        /// </summary>
        public static string vertMinMaxVal_REQ {
            get {
                return ResourceManager.GetString("vertMinMaxVal_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical minimum extent must be a real value.
        /// </summary>
        public static string vertMinVal_REAL {
            get {
                return ResourceManager.GetString("vertMinVal_REAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical minimum extent is required.
        /// </summary>
        public static string vertMinVal_REQ {
            get {
                return ResourceManager.GetString("vertMinVal_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voice phone number is required.
        /// </summary>
        public static string voiceNum_FGDC_REQ {
            get {
                return ResourceManager.GetString("voiceNum_FGDC_REQ", resourceCulture);
            }
        }
    }
}
