/*
Copyright 2019 Esri
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.​
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace metadata_toolkit_wizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("metadata_toolkit_wizard.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ArcGIS Pro add-in project. Project is missing required configuration file &apos;Config.daml&apos;. Unable to add new add-in item to this project..
        /// </summary>
        internal static string AddItemConfigFileNotFound {
            get {
                return ResourceManager.GetString("AddItemConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ArcGIS Pro SDK {0} for .NET requires ArcGIS Pro {0} to be installed..
        /// </summary>
        internal static string ArcGISProMissing {
            get {
                return ResourceManager.GetString("ArcGISProMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Pro {0} not found..
        /// </summary>
        internal static string ArcGISProMissingTitle {
            get {
                return ResourceManager.GetString("ArcGISProMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Pro {0} SDK for .NET cannot be installed over a beta version of ArcGIS Pro..
        /// </summary>
        internal static string BetaError {
            get {
                return ResourceManager.GetString("BetaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.daml not found..
        /// </summary>
        internal static string ConfigFileNotFoundException {
            get {
                return ResourceManager.GetString("ConfigFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Config.daml DAML file cannot be found. The control will still be added. The Config.daml must be updated by hand..
        /// </summary>
        internal static string ConfigFileNotFoundWarning {
            get {
                return ResourceManager.GetString("ConfigFileNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Pro {0} SDK for .NET cannot be installed over ArcGIS Pro {1}..
        /// </summary>
        internal static string GeneralVersionError {
            get {
                return ResourceManager.GetString("GeneralVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install location of ArcGIS Pro cannot be found. Please check your registry for {0}.
        /// </summary>
        internal static string InstallDirMissing {
            get {
                return ResourceManager.GetString("InstallDirMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArcGIS Pro {0} is not installed..
        /// </summary>
        internal static string SupportedProVersionMissing {
            get {
                return ResourceManager.GetString("SupportedProVersionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported ArcGIS Pro version not found.
        /// </summary>
        internal static string SupportedVersionTitle {
            get {
                return ResourceManager.GetString("SupportedVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of ArcGIS Pro cannot be determined. Please check your registry for {0}.
        /// </summary>
        internal static string VersionMissing {
            get {
                return ResourceManager.GetString("VersionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wizard has been cancelled.
        /// </summary>
        internal static string WizardCancelled {
            get {
                return ResourceManager.GetString("WizardCancelled", resourceCulture);
            }
        }
    }
}
